[package]
name = "tensorimage-core"
version = "0.1.0"
edition = "2021"

[dependencies]
image = { version = "0.25", default-features = false, features = ["png", "webp", "avif"] }
fast_image_resize = "6"
thiserror = "2"
turbojpeg = "1.3"
rayon = "1.10"
kamadak-exif = "0.5"
webp = "0.3"
