[package]
name = "tensorimage-python"
version = "0.1.0"
edition = "2021"

[lib]
name = "_tensorimage"
crate-type = ["cdylib"]

[dependencies]
pyo3 = { version = "0.28", features = ["extension-module"] }
numpy = "0.28"
tensorimage-core = { path = "../tensorimage-core" }
